enum
{
    Vertex_Shader_NORMAL,
    Vertex_Shader_GAUSSIANBLUR,
    Vertex_Shader_TEXTURE_NORMAL,
    Total_Vertex_Shader_Number,
};
enum
{
    Fragment_Shader_NORMAL,
    Fragment_Shader_GAUSSIANBLUR,
    Fragment_Shader_TEXTURE_NORMAL,
    Total_Fragment_Shader_Number,
};
enum
{
    Shader_Program_NORMAL,
    Shader_Program_GAUSSIANBLUR,
    Shader_Program_TEXTURE_NORMAL,
    Total_Shader_Program_Number,
};
enum
{
    ATTRIBUTES_POSITION,
    ATTRIBUTES_POSITION2,
    ATTRIBUTES_UV2,
    ATTRIBUTES_POSITION3,
    ATTRIBUTES_UV3,
    ATTRIBUTES_COLOR,
    Total_Attributes_Number,
};
enum
{
    UNIFORMS_TRANSLATE,
    UNIFORMS_SCALE,
    Total_Uniforms_Number,
};


enum
{
    TEXTURES_PAPER,
    Total_Texture_Number,
};